@extends('layouts.app')
@section('content')
<div class="section-head"><div><div class="eyebrow">The business edition</div><h1>Business</h1></div><form class="search" role="search" method="get" action="{{ route('news.index') }}"><input aria-label="Search headlines or authors" name="q" value="{{ $q }}" placeholder="Search headlines or authors" maxlength="200">@if($category)<input type="hidden" name="category" value="{{ $category }}">@endif<button type="submit">Search</button></form></div>
<nav class="categories" aria-label="News categories"><a class="{{ !$category ? 'active' : '' }}" href="{{ route('news.index',['q'=>$q]) }}">All stories</a>@foreach($categories as $item)<a class="{{ $category===$item ? 'active' : '' }}" href="{{ route('news.index',['category'=>$item,'q'=>$q]) }}">{{ $item }}</a>@endforeach</nav>
@foreach($errors->all() as $error)<p class="error">{{ $error }}</p>@endforeach
<p class="result-label">{{ $articles->total() }} stories @if($q) · Results for “{{ $q }}” @else · From the September 24 snapshot @endif</p><div class="grid">
@forelse($articles as $article)<article class="card"><a href="{{ route('news.show',$article) }}" tabindex="-1" aria-hidden="true"><div class="media {{ !$article->image ? 'missing' : '' }}">@if($article->image)<img class="photo" src="{{ $article->image }}" alt="" loading="{{ $loop->first ? 'eager' : 'lazy' }}">@else<div class="photo"></div>@endif</div></a><span class="tag">{{ $article->category }}</span><h2><a href="{{ route('news.show',$article) }}">{{ $article->title }}</a></h2><div class="byline">{{ $article->author }} · {{ $article->published_at->format('M j, Y') }}</div><p class="excerpt">{{ $article->excerpt }}</p></article>
@empty<div class="empty"><h2>No stories found</h2><p>Try another headline, author or category.</p><a class="button" href="{{ route('news.index') }}">View all stories</a></div>@endforelse</div>
@if($articles->hasPages())<nav class="pager" aria-label="Pagination">@if(!$articles->onFirstPage())<a href="{{ $articles->previousPageUrl() }}" rel="prev">← Previous</a>@endif<span>Page {{ $articles->currentPage() }} of {{ $articles->lastPage() }}</span>@if($articles->hasMorePages())<a href="{{ $articles->nextPageUrl() }}" rel="next">Next →</a>@endif</nav>@endif
@endsection
